version: "3.3"
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: spark
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3306:3306"
  php:
    image: php:7.4.2-fpm
    build:
      context: .
      dockerfile: Dockerfile
    hostname: php
    ports:
      - "9000:9000"
    volumes:
      - "./:/var/www/html"
    working_dir: "/var/www/html"
    depends_on:
      - mysql
  nginx:
    image: webdevops/nginx
    hostname: nginx
    environment:
      WEB_DOCUMENT_ROOT: /var/www/html
    ports:
      - "8000:80"
    volumes:
      - "./:/var/www/html"
    depends_on:
      - php

